version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elearning_app
    depends_on:
      - db
      - redis
    environment:
      - PORT=8080
      - DB_HOST=db                          # ✅ FIXED: should match the service name of the database
      - DB_PORT=5432
      - DB_USER=elearning_user
      - DB_PASSWORD=elearning_password
      - DB_NAME=elearning
      - DB_SSLMODE=disable
      - DATABASE_URL=postgres://elearning_user:elearning_password@db:5432/elearning?sslmode=disable  # ✅ ensure it matches the other DB_* values
      - JWT_SECRET=your_super_secret_key
      - JWT_REFRESH_SECRET=your_super_refresh_secret_key
      - REDIS_URL=redis://redis:6379
      - ENV=development
    volumes:
      - ./pkg/config/.env:/app/.env
      - ./internal/config/config.yaml:/app/config/config.yaml
    ports:
      - "8080:8080"
    networks:
      - elearning_network

  db:
    image: postgres:12
    container_name: postgress_db
    environment:
      POSTGRES_DB: elearning
      POSTGRES_USER: elearning_user
      POSTGRES_PASSWORD: elearning_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # you connect externally on port 5433, but internal port is 5432
    networks:
      - elearning_network

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - elearning_network

volumes:
  pgdata:

networks:
  elearning_network:
    driver: bridge
